### ISSUE TITLE
configparser.py ,raise KeyError(key),KeyError: 'display'

### ISSUE THREAD

**Issue by zgjssyjw** [power-helper/power-helper-backup20210704#102]
**系统版本，包含位数**：win10 64位

**python版本**：3.7.1

**软件/源码版本**：20210520

**浏览器、驱动版本**：chrome  89.0.4389.72

-----

## 全部报错
答：Traceback (most recent call last):
  File "d:/Documents/python_code/TechXueXi-20210520/SourcePackages/pandalearning.py", line 45, in <module>
    if(cfg['display']['banner'] != "false"): # banner文本直接硬编码，不要放在ini中
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'display'

**Comment by TCPsoftware** [comment]
找到config/main.ini，检查下有无
```
; 显示设置。
[display]
; 显示banner (true/false)
banner = true
```
注意banner前面没有分号
