### ISSUE TITLE
请求略过视频题目后添加冷却时间/答题完成之后报错/获取提示仍为上一题的提示

### ISSUE THREAD

**Issue by xxxxuanran** [power-helper/power-helper-backup20210704#106]
**系统版本，包含位数**：Windows 21H1 x64

**python版本**：Python 3.8.5

**软件/源码版本**：v20210521

**浏览器、驱动版本**：Chrome 90.0.4430.85 + ChromeDriver 90.0.4430.24

-----

## 详细描述
答：两个错误看起来基本相同，不另新开 issues。
## 全部报错
答：
视频题目报错如下
```
Traceback (most recent call last):
  File ".\pandalearning.py", line 96, in <module>
    daily(cookies, scores)
  File "E:\Project\TechXueXi\SourcePackages\pdlearn\answer_question.py", line 48, in daily
    tips, tip_full_text = driver_daily._view_tips()
ValueError: not enough values to unpack (expected 2, got 0)
```

每周答题完成后报错如下
```
Traceback (most recent call last):
  File ".\pandalearning.py", line 99, in <module>
    weekly(cookies, scores)
  File "E:\Project\TechXueXi\SourcePackages\pdlearn\answer_question.py", line 243, in weekly
    tips, tip_full_text = driver_weekly._view_tips()
ValueError: not enough values to unpack (expected 2, got 0)
```

## 建议
答：
1. 视频题目单独设置更大的冷却时间
2. 在`answer_question.py`文件的`q_body = driver_daily.driver.find_element_by_css_selector(".q-body")`前添加`try`，以避免结束答题后取不到`.q-body`元素时抛出异常结束运行。`tips, tip_full_text = driver_weekly._view_tips()`同理
3. 最新dev已修复，等同步。

**Comment by zgjssyjw** [comment]
视频题目，建议形成题库，优先从题库匹配答案
