### ISSUE TITLE
Chrome version must be between 70 and 73

### ISSUE THREAD

**Issue by thinkrecord** [power-helper/power-helper-backup20210704#113]
**系统版本，包含位数**：win10x64

**软件/源码版本**：v20210521 完整包

-----

## 详细描述
答：v20210521 完整包双击运行，3选项

## 全部报错
答：

```
============================================================
Mydriver初始化失败
============================================================
Traceback (most recent call last):
  File "pandalearning.py", line 74, in <module>
  File "pdlearn\mydriver.py", line 80, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68,platform=Windows NT 10.0.18362 x86_64)

[27564] Failed to execute script pandalearning
[*] 版本信息网络错误
```

**Comment by thinkrecord** [comment]
完整版的 chrome 和 driver 是直接复制原来的，不可能有问题，但报错不匹配。

可能是系统安装的新版谷歌浏览器 88.0.4302.0 造成?

**Comment by Nyanners1** [comment]
![image](https://user-images.githubusercontent.com/84719520/119354098-3f8a8d00-bcd6-11eb-8767-ad80d50a6915.png)
类似的问题，打开直接闪退。win10 21h1

**Comment by thinkrecord** [comment]
问题是 win 下不应该运行 80 这一行：

https://github.com/TechXueXi/TechXueXi/blob/8e65366ebcb91d23b82e8e3b26b130a544e4b685/SourcePackages/pdlearn/mydriver.py#L67-L80

应该是路径问题

**Comment by zz33600606** [comment]
请问一下楼主怎么下到完整包

**Comment by Masofish** [comment]
> 问题是 win 下不应该运行 80 这一行：
> 
> https://github.com/TechXueXi/TechXueXi/blob/8e65366ebcb91d23b82e8e3b26b130a544e4b685/SourcePackages/pdlearn/mydriver.py#L67-L80
> 
> 应该是路径问题

你好，请问你解决了么，我也是这个问题，老版本用不了，新版本替换后登不上去，Mydriver初始化失败

**Comment by lhz15621009715** [comment]
> > 问题是 win 下不应该运行 80 这一行：
> > https://github.com/TechXueXi/TechXueXi/blob/8e65366ebcb91d23b82e8e3b26b130a544e4b685/SourcePackages/pdlearn/mydriver.py#L67-L80
> > 
> > 应该是路径问题
> 
> 你好，请问你解决了么，我也是这个问题，老版本用不了，新版本替换后登不上去，Mydriver初始化失败

将chrome放置在sourcepackages文件目录下

**Comment by keke1975** [comment]
把TechXueXi_20210521.exe这个文件，放入chrome这个文件夹内并在这个文件夹内运行它。

**Comment by dalu-test** [comment]
我也是这个报错。
![111](https://user-images.githubusercontent.com/19725833/120731044-5b333600-c515-11eb-865c-b8e696c43704.jpg)

**Comment by zheNezha** [comment]
我也是这个报错
![111](https://user-images.githubusercontent.com/19725833/120731116-80c03f80-c515-11eb-8aff-71c0c505ce76.jpg)
