### ISSUE TITLE
每周答题BUG提交

### ISSUE THREAD

**Issue by wangzi9118** [power-helper/power-helper-backup20210704#115]
**系统版本，包含位数**：

**python版本**：3.9

**软件/源码版本**：20210521

**浏览器、驱动版本**：Chrome 90

-----

## 详细描述
答：当每周的答题全部为已作答状态时，软件运行出错

## 全部报错
答：本月
2021年5月第四周答题
已作答+5积分
重新答题
2021年5月第三周答题
已作答+5积分
重新答题
2021年5月第二周答题
已作答+5积分
重新答题
2021年5月第一周答题
已作答+5积分
重新答题
没有可点击的【查看提示】按钮
Traceback (most recent call last):
  File "D:\TechXueXi\TechXueXi-master\TechXueXi-master\SourcePackages\pandalearning.py", line 99, in <module>
    weekly(cookies, scores)
  File "D:\TechXueXi\TechXueXi-master\TechXueXi-master\SourcePackages\pdlearn\answer_question.py", line 243, in weekly
    tips, tip_full_text = driver_weekly._view_tips()
ValueError: not enough values to unpack (expected 2, got 0)

Process finished with exit code 1

## 建议
答：

**Comment by zgjssyjw** [comment]
同一版本，出现同样的问题

填空题
电影《红色娘子军》中，琼花在执行一次侦察任务时遇到地主南霸天，世代冤仇涌上心头，她不顾纪律开枪打伤了南霸天。连长批评她道：“你这是勇敢吗？你不是三
个月前的野姑娘，你是”。
没有可点击的【查看提示】按钮
Traceback (most recent call last):
  File "d:/jiangwei/Documents/python_code/TechXueXi-20210521/SourcePackages/pandalearning.py", line 96, in <module>
    daily(cookies, scores)
  File "d:\jiangwei\Documents\python_code\TechXueXi-20210521\SourcePackages\pdlearn\answer_question.py", line 48, in daily
    tips, tip_full_text = driver_daily._view_tips()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by cychina** [comment]
我也遇到这个问题，每周答题如果之前已经全部完成了，会报错！

**Comment by YeQiuO** [comment]
问题出在找不到答案的时候直接返回了一个空字符串
![image](https://user-images.githubusercontent.com/45990941/120593004-63d23080-c471-11eb-86e0-ca065b6d91b6.png)

我尝试了 return None, None 还没确定是否可行

类似的问题，在找不到答案的时候，一直 continue 能否改成随即填写一个错误答案嫩？
![image](https://user-images.githubusercontent.com/45990941/120593137-a1cf5480-c471-11eb-9fe6-39c8fa853bf7.png)

**Comment by TCPsoftware** [comment]
上个提交遗留下来的问题 🤔
新提交中将 `return ""` 改为了 `return [],""` ，返回两个结果，不至于语法报错
