### ISSUE TITLE
get_video_links获取失败

### ISSUE THREAD

**Issue by lvzhenbo** [power-helper/power-helper-backup20210704#124]
**系统版本，包含位数**：Windows 10 v21H1 64位

**python版本**：

**软件/源码版本**：v20210521

**浏览器、驱动版本**：

-----

## 详细描述
答：二维码扫完后就闪退

## 全部报错
答：
get_video_links获取失败
========================================================================================================================Traceback (most recent call last):
  File "pandalearning.py", line 613, in <module>
  File "pandalearning.py", line 52, in show_score
  File "pdlearn\score.py", line 13, in get_score
  File "json\__init__.py", line 359, in loads
TypeError: __init__() got an unexpected keyword argument 'encoding'
[9608] Failed to execute script pandalearning

**Comment by lvzhenbo** [comment]
我知道咋回事了，新打包的单文件不是最新版
