### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by MrWj** [power-helper/power-helper-backup20210704#127]
**系统版本，包含位数**：macOS 10.15.7 

**python版本**：3.9.5

主分支源码运行

get_video_links获取失败
========================================================================================================================
Traceback (most recent call last):
  File "../SourcePackages/pandalearning.py", line 613, in <module>
    total, each = show_score(cookies)
  File "..//SourcePackages/pandalearning.py", line 52, in show_score
    total, each = score.get_score(cookies)
  File "../SourcePackages/pdlearn/score.py", line 13, in get_score
    total = int(json.loads(total, encoding="utf8")["data"]["score"])
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by tirkarthi** [comment]
encoding parameter to json.loads was deprecated and removed in Python 3.9 : https://bugs.python.org/issue39377

**Comment by EwaneGao** [comment]
Windows系统 python3.8.6 同样遇到，求帮

**Comment by TCPsoftware** [comment]
代码已更新。请使用新版本
目前代码中 json.loads 没有用到 encoding
