### ISSUE TITLE
windows 环境运行pandalearning.exe报错

### ISSUE THREAD

**Issue by smileMurphy** [power-helper/power-helper-backup20210704#13]
C:\Users\murphy.ZQ\Desktop>pandalearning.exe
开启： 获取更新信息...
熊猫学习唯一下载地址为 https://github.com/Alivon/Panda-Learning
========================================================================================================================
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "site-packages\selenium\webdriver\common\service.py", line 76, in start
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 174, in <module>
  File "pandalearning.py", line 14, in user_flag
  File "pdlearn\mydriver.py", line 47, in __init__
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
  File "site-packages\selenium\webdriver\common\service.py", line 83, in start
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[8336] Failed to execute script pandalearning

**Comment by thinkrecord** [comment]
如果您下载的win完整版，请检查chrome文件夹中是否有chromedriver.exe

**Comment by smileMurphy** [comment]
需要下载完整版运行，明白了，谢谢老铁
