### ISSUE TITLE
答完每日答题后报错

### ISSUE THREAD

**Issue by jupitersh** [power-helper/power-helper-backup20210704#131]
**系统版本，包含位数**：win10 64位

**python版本**：3.8.5

**软件/源码版本**：v20210521

**浏览器、驱动版本**：chrome=91.0.4472.77

## 详细描述
答：答完每日答题后报错

## 全部报错
```
Traceback (most recent call last):
  File "pandalearning.py", line 96, in <module>
    daily(cookies, scores)
  File "D:\OneDrive\桌面\TechXueXi-20210521\SourcePackages\pdlearn\answer_question.py", line 43, in daily
    q_body = driver_daily.driver.find_element_by_css_selector(".q-body")
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".q-body"}
  (Session info: chrome=91.0.4472.77)
```
![image](https://user-images.githubusercontent.com/55310213/120886418-6aeb7100-c620-11eb-847a-519f42efa896.png)

**Comment by TCPsoftware** [comment]
上个提交遗留下来的问题。
新提交已解决

**Comment by jupitersh** [comment]
v20210605版本报错，错误如下，同样的环境，换成v20210521就没有问题
```
============================================================
Mydriver初始化失败
============================================================
Traceback (most recent call last):
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Softwares\Python3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Softwares\Python3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 74, in <module>
    driver_login = Mydriver(nohead=False)
  File "C:\Users\Pepper\Downloads\TechXueXi-20210605\SourcePackages\pdlearn\mydriver.py", line 80, in __init__
    self.driver = self.webdriver.Chrome(executable_path="./chrome/chromedriver.exe",chrome_options=self.options)
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Softwares\Python3\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20210605
[*] 最新版本为：v20210521
[*] 当前不是最新版本，建议更新
[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =[*] =
[*] 更新提要：
[*] 当前最新版本为v20210521版，此版提供打包好的单文件。
[*] 请更新！！！
[*] - 这一版更新：
[*] - 略
[*] - 科技强国官方网站：https://techxuexi.js.org
[*]
```

**Comment by TCPsoftware** [comment]
已解决
