### ISSUE TITLE
碰到视频题就卡住出错  帮忙看看什么情况

### ISSUE THREAD

**Issue by yunv7** [power-helper/power-helper-backup20210704#138]
电影《童年周恩来》中，为了补贴家用和还债，周恩来带着两个弟弟挖浦儿菜来卖，这种野菜又被称作，相传南宋时梁红玉、韩世忠镇守淮安，就是靠吃这种菜坚持到最后胜利。
有可点击的【查看提示】按钮
获取提示： []
本题没有提示
Traceback (most recent call last):
  File "./pandalearning.py", line 96, in <module>
    daily(cookies, scores)
  File "D:\download\xuexi\pdlearn\answer_question.py", line 394, in daily
    answer_question(quiz_type, cookies, scores, score_all, quiz_xpath, category_xpath)
  File "D:\download\xuexi\pdlearn\answer_question.py", line 158, in answer_question
    sleep(3)
NameError: name 'sleep' is not defined

这是出错信息 我找到158行的sleep(3)改成time sleep(3)，又开始无限循环点提示 这是正常的吗？

**Comment by OliverYmy** [comment]
视频题没有提示的，得自己做

**Comment by TCPsoftware** [comment]
每日答题sleep问题已修复，用最新版本代码
