### ISSUE TITLE
Message: 'chromedriver.exe' executable needs to be in PATH - v20210605

### ISSUE THREAD

**Issue by zoyao** [power-helper/power-helper-backup20210704#145]
**系统版本，包含位数**：win10 64位

**python版本**：3.9.4

**软件/源码版本**：v20210605

**浏览器、驱动版本**：91.0.4472.101

-----

## 详细描述
Mydriver初始化失败

## 全部报错
```
请选择模式（输入对应数字）并回车： 3
开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
未找到有效登录信息，需要登录
============================================================
Mydriver初始化失败
============================================================
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tech\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "D:\ProgramData\Anaconda3\envs\tech\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Anaconda3\envs\tech\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\soft\TechXueXi-20210605\SourcePackages\pandalearning.py", line 74, in <module>
    driver_login = Mydriver(nohead=False)
  File "C:\soft\TechXueXi-20210605\SourcePackages\pdlearn\mydriver.py", line 80, in __init__
    self.driver = self.webdriver.Chrome(executable_path="./chrome/chromedriver.exe",chrome_options=self.options)
  File "D:\ProgramData\Anaconda3\envs\tech\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "D:\ProgramData\Anaconda3\envs\tech\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

## 建议
将File "\SourcePackages\pdlearn\mydriver.py", line 80修改为如下后运行正常
```
//self.driver = self.webdriver.Chrome(executable_path="./chrome/chromedriver.exe",chrome_options=self.options)
self.driver = self.webdriver.Chrome(chrome_options=self.options)
```
对chromedriver不太熟悉，不知是代码问题还是本人的chromedriver配置方式有误，截图附上环境变量path配置，chromedriver路径为C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe
![image](https://user-images.githubusercontent.com/23072762/122636140-35fc1580-d11a-11eb-8a58-ec985ec43c60.png)

**Comment by TCPsoftware** [comment]
已更新源码
