### ISSUE TITLE
用pyinstaller编译的总是不能执行。

### ISSUE THREAD

**Issue by gulshj** [power-helper/power-helper-backup20210704#36]
pyinstaller -F pandalearning.py
Traceback (most recent call last):
  File "E:\Users\gulshj\Desktop\TechXueXi-master\SourcePackages\pandalearning.py", line 4, in <module>
    from pdlearn import version
  File "c:\users\gulshj\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.p
y", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pdlearn\version.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[9780] Failed to execute script pandalearning

以前还是熊猫时正常编译的，现在不能执行了，想改改，该怎么编译？

**Comment by thinkrecord** [comment]
`ModuleNotFoundError: No module named 'requests'`

没装这个包
