### ISSUE TITLE
win7出错

### ISSUE THREAD

**Issue by womengnan** [power-helper/power-helper-backup20210704#45]
正在联网获取更新信息...

DevTools listening on ws://127.0.0.1:59956/devtools/browser/4c5696eb-3a31-4cf8-9
a41-d803736cf484
TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
程序版本为：v20200928，
最新版本为：v20200928
================================================================================
========================================
================================================================================
========================================
更新显示不会打断之前输入等操作，请继续......
================================================================================
========================================
Mydriver初始化失败
================================================================================
========================================
Traceback (most recent call last):
  File "pandalearning.py", line 612, in <module>
  File "pandalearning.py", line 20, in user_flag
  File "pdlearn\mydriver.py", line 60, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not crea
ted
from disconnected: unable to connect to renderer
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65af
e72),platform=Windows NT 6.1.7601 SP1 x86_64)

[18180] Failed to execute script pandalearning

**Comment by lijinlong2baby** [comment]
![IMG_20201210_103240](https://user-images.githubusercontent.com/47732238/101738752-93773000-3b01-11eb-910b-04353435c01a.jpg)
我也出错 Windowsx86和x64都试过了都出错 下载页面的依赖也安装了不行

**Comment by HiMaico** [comment]
解决了嘛？怎么搞这个问题。

**Comment by drw2005** [comment]
我也是这问题，哪位大佬指点一下啊。

**Comment by zhaojie199512** [comment]
我解决了，是 win7 不支持python 3.8.6,需要升级win7 到sp1 版本（网上搜win7 sp1 补丁包）就可以运行了，不过文章和学习依旧无法使用，其他功能正常。

**Comment by TCPsoftware** [comment]
chrome版本和chrome driver版本不匹配有可能导致此问题，但此处都是73版本的
可能是偶发性问题。
重新运行还是会出现吗？
如一直出现尝试升级系统至Windows10？
