### ISSUE TITLE
无法成功打包bug（最新版没有可执行文件了是吧？）

### ISSUE THREAD

**Issue by mapleshadow** [power-helper/power-helper-backup20210704#75]
RT。。。。。。。。。。抱歉我偷懒了，没人回答我还是去用python了

**Comment by Mo-Yuxi** [comment]
暂时是没有的   你可以自行使用pyinstaller打包

**Comment by mapleshadow** [comment]
> 暂时是没有的 你可以自行使用pyinstaller打包

感谢感谢，你们辛苦了

**Comment by wujbclzw** [comment]
1. 把旧版本的chrome文件夹的路径放在系统的path环境变量中
2. 安装一下Python，以及requirements.txt 中的依赖库，运行SourcePackages\pandalearning.py 文件。

**Comment by mapleshadow** [comment]
> 1. 把旧版本的chrome文件夹的路径放在系统的path环境变量中
> 2. 安装一下Python，以及requirements.txt 中的依赖库，运行SourcePackages\pandalearning.py 文件。

感谢感谢

**Comment by mapleshadow** [comment]
> 暂时是没有的 你可以自行使用pyinstaller打包

我用这个打包出来的exe闪退

**Comment by mapleshadow** [comment]
> 暂时是没有的 你可以自行使用pyinstaller打包

**Comment by cjh0613** [comment]
~~这是我打包的 techxuexi 单文件，帮忙试试能否使用~~

已测试，不能用

**Comment by mapleshadow** [comment]
> ~这是我打包的 techxuexi 单文件，帮忙试试能否使用~
> 
> 已测试，不能用

是的，一旦打包成EXE就不能运行，不知所以哦。。。。

**Comment by cjh0613** [comment]
> > ~这是我打包的 techxuexi 单文件，帮忙试试能否使用~
> > 已测试，不能用
> 
> 是的，一旦打包成EXE就不能运行，不知所以哦。。。。

应该是文件`config.py`（ https://github.com/TechXueXi/TechXueXi/blob/d5b864491e6e8727e0618f81d3dac3d29aa72be6/SourcePackages/pdlearn/config.py ）造成的：


```python
import os
import sys
from configparser import ConfigParser

cfg = ConfigParser()

os.chdir(sys.path[0]) # 切换pwd到python文件路径，避免找不到相对路径下的ini  ## 应该是这里
if(not os.path.exists("config")):
    os.mkdir("config")
    if(not os.path.exists("config/main.ini")):
        # write_default_ini()
        input("缺少配置文件 config/main.ini，请检查.")
        exit()
cfg.read('./config/main.ini', encoding='utf-8')

```

存在bug，造成打包的文件报错：

```
Traceback (most recent call last):
  File "pandalearning.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "pdlearn\config.py", line 7, in <module>
NotADirectoryError: [WinError 267] 目录名称无效。: '……\\base_library.zip'
[53664] Failed to execute script pandalearning
```

**Comment by cjh0613** [comment]
@TCPsoftware

**Comment by TCPsoftware** [comment]
试一下把
os.chdir(sys.path[0]) # 切换pwd到python文件路径，避免找不到相对路径下的ini
放到pandalearning.py呢？

**Comment by TCPsoftware** [comment]
做了一些修改， @cjh0613

**Comment by cjh0613** [comment]
> 做了一些修改， 

@TCPsoftware ，打包后的文件依然报错：

```
Traceback (most recent call last):
  File "pandalearning.py", line 40, in <module>
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI323602\\base_library.zip'
[61236] Failed to execute script pandalearning
```

**Comment by lingyust** [comment]
> > > ~这是我打包的 techxuexi 单文件，帮忙试试能否使用~
> > > 已测试，不能用
> > 
> > 
> > 是的，一旦打包成EXE就不能运行，不知所以哦。。。。
> 
> 应该是文件`config.py`（ https://github.com/TechXueXi/TechXueXi/blob/d5b864491e6e8727e0618f81d3dac3d29aa72be6/SourcePackages/pdlearn/config.py ）造成的：
> 
> ```python
> import os
> import sys
> from configparser import ConfigParser
> 
> cfg = ConfigParser()
> 
> os.chdir(sys.path[0]) # 切换pwd到python文件路径，避免找不到相对路径下的ini  ## 应该是这里
> if(not os.path.exists("config")):
>     os.mkdir("config")
>     if(not os.path.exists("config/main.ini")):
>         # write_default_ini()
>         input("缺少配置文件 config/main.ini，请检查.")
>         exit()
> cfg.read('./config/main.ini', encoding='utf-8')
> ```
> 
> 存在bug，造成打包的文件报错：
> 
> ```
> Traceback (most recent call last):
>   File "pandalearning.py", line 11, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
>   File "pdlearn\config.py", line 7, in <module>
> NotADirectoryError: [WinError 267] 目录名称无效。: '……\\base_library.zip'
> [53664] Failed to execute script pandalearning
> ```

确实，打包之后就出现这样的问题，不知道怎么解决

**Comment by TCPsoftware** [comment]
或许是打包就不能用os.chdir(sys.path[0])，试着找一下有没有其他类似函数可以实现相对目录的寻找呢

**Comment by TCPsoftware** [comment]
> 或许是打包就不能用os.chdir(sys.path[0])，试着找一下有没有其他类似函数可以实现相对目录的寻找呢

有一个pathlib库可以试试用

**Comment by a18ccms** [comment]
把`os.chdir(sys.path[0])`
改成    
 ```
base_path = getattr(sys, '_MEIPASS', os.path.abspath('.'))
 os.chdir(base_path)
```
pytinstaller就可以正常打包了。
还有就是config.ini文件中的SendLoginQRcode注解去掉，并设置0.代码中没对这里进行判断。注解了代码还调用。导致代码运行错误。
```
[addition]
; 是否通过邮件微信或其他方式发送登录二维码？此功能暂不支持。（此配置项暂未应用至代码。）
SendLoginQRcode=0
```

**Comment by TCPsoftware** [comment]
print(os.path.dirname(os.path.realpath(sys.argv[0])))  ，经测试可用。
参考 https://www.jb51.net/article/162784.htm

对于python xx.py，sys.argv[0]为xx.py，os.path.realpath(sys.argv[0])为py文件完整路径，
os.path.dirname(os.path.realpath(sys.argv[0]))为完整路径的文件夹名

对于exe，sys.argv[0]为xx.exe，os.path.realpath(sys.argv[0])为exe文件完整路径，
os.path.dirname(os.path.realpath(sys.argv[0]))为完整路径的文件夹名
