### ISSUE TITLE
更新到Chrome90之后无法正常运行

### ISSUE THREAD

**Issue by xxxxuanran** [power-helper/power-helper-backup20210704#83]
**系统版本，包含位数**：
Windows10 21H1 x64

**python版本**：
Python 3.8.5

**软件/源码版本**：
v20210316

**浏览器、驱动版本**：
Chrome 90.0.4430.85 x64
ChromeDriver 90.0.4430.24

-----

## 详细描述
答：
更新到Chrome 90之后无法运行，Log如下

## 全部报错
答：
```
开启： 文章学习开启： 视频学习


DevTools listening on ws://127.0.0.1:56575/devtools/browser/fbf488e3-baca-4d7e-8b6f-c8e3ef9e7806

DevTools listening on ws://127.0.0.1:56577/devtools/browser/e19e8f08-43f8-48a3-bb03-2d2060ab0391
[0424/002057.221:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is swiftshader
[0424/002057.225:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is swiftshader
视频学习检测到异常：Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: headless chrome=90.0.4430.85)

文章学习检测到异常：Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: headless chrome=90.0.4430.85)

开始每日答题……

DevTools listening on ws://127.0.0.1:56597/devtools/browser/b2827af7-68ee-4d39-9561-370f15b6b956
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化
Traceback (most recent call last):
  File "./SourcePackages/pandalearning.py", line 86, in <module>
  File "E:\Project\TechXueXi\SourcePackages\pdlearn\answer_question.py", line 23, in daily
    driver_daily.set_cookies(cookies)
  File "E:\Project\TechXueXi\SourcePackages\pdlearn\mydriver.py", line 133, in set_cookies
    self.driver.add_cookie({k: cookie[k] for k in cookie.keys()})
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=90.0.4430.85)
```

## 建议
答：修复在Chrome 90 Version上的正常运行

**Comment by saltfish13** [comment]
我也遇到了相同的问题，可以说是很难过了

**Comment by akatsukikyouko** [comment]
同样的问题，找不到domain这个cookie？

**Comment by shq1234** [comment]
遇到这个问题的把浏览器的自动更新给关了，然后不用降chrome的版本，把chromedriver的版本替换成89的即可解决问题！

**Comment by pipeddev** [comment]
I have the same problem, currently I am. working with this version webdriverio 5.16.15

**Comment by xifen523** [comment]
选择89版本的驱动就行

**Comment by LevineWoo** [comment]
请问有知道怎么换账号或者多号选择的吗？

**Comment by TCPsoftware** [comment]
> 请问有知道怎么换账号或者多号选择的吗？

扫码登陆时使用另外的账号扫码？

**Comment by HJL-echoandy** [comment]
修复在Chrome 90 Version上的正常运行
什么意思
