### ISSUE TITLE
SendLoginQRCode获取失败

### ISSUE THREAD

**Issue by kid424** [power-helper/power-helper-backup20210704#95]
**系统版本，包含位数**：Raspberry Pi OS with desktop (Debian Buster) 32bit

**python版本**：2.7.16

**软件/源码版本**：master branch commit 93c61bf10009e29bdca650d4987853e373381524

**浏览器、驱动版本**：官方源chromium

-----

## 详细描述
答：运行后选择模式3，浏览器打开二维码页面后报错

## 全部报错
答：
Traceback (most recent call last):
  File "pandalearning.py", line 73, in <module>
    cookies = driver_login.login()
  File "/home/pi/Desktop/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 155, in login
    cookie_list = self.get_cookie_from_network()
  File "/home/pi/Desktop/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 113, in get_cookie_from_network
    if cfg["addition"]["SendLoginQRcode"] == "1":
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'SendLoginQRcode'

## 建议
答：看报错是因为没有读取到配置中的addition项里的SendLoginQRcode选项，手动将配置文件中此项取消注释并设为0后恢复可用。建议添加非空判断或者修改配置文件。

**Comment by xuhn** [comment]
使用新版，无须更改配置中  addition里的SendLoginQRcode选项
